refactor: modularize maven proj with shared module event

diff --git a/deploying/run_local b/deploying/run_local
--- a/deploying/run_local
+++ b/deploying/run_local
@@ -1,9 +1,11 @@
 #!/bin/bash
 
 BASE_DIR=$(realpath "$(dirname "$0")"/..)
-JAVA_DIR="$BASE_DIR/java-cep"
+JAVA_BASE_DIR="$BASE_DIR/mama-module"
+JAVA_PROJ_DIR="$BASE_DIR/mama-module/java-cep"
 PY_DIR="$BASE_DIR/python"
 DEPLOYING_DIR="$BASE_DIR/deploying"
+INFLATED_RATES=0
 
 wait_until_middle_of_minute() {
   seconds_on_clock=$(date "+%-S")
@@ -11,12 +13,36 @@ wait_until_middle_of_minute() {
   sleep $time_to_30s
 }
 
-if (( $# < 2 )); then
-  echo "Usage: run INPUT_DIR N [RUN_DURATION]";
+usage() {
+  echo "Usage: run [OPTIONS] INPUT_DIR N [RUN_DURATION]";
   echo "Deploys configs and runs all nodes."
   echo "INPUT_DIR: path to a folder with config_i.json and trace_i.json for each node i";
   echo "N: number of nodes";
   echo "RUN_DURATION: sleep time, i.e. expected duration (default is 10m)";
+  echo "";
+  echo "Options:";
+  echo "  -i: Flag that enables inflated rates";
+}
+
+# Process options
+while getopts ":i" opt; do
+  case $opt in
+    i)
+      INFLATED_RATES=1
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      usage
+      exit 1
+      ;;
+  esac
+done
+
+# Shift off the options and optional --
+shift $((OPTIND - 1))
+
+if (( $# < 2 )); then
+  usage
   exit 1
 else
   INPUT_DIR="$(realpath $1)"
@@ -24,25 +50,34 @@ else
   RUN_DURATION_MIN=${3:-10}  # Use the third argument, or set default value
 fi;
 
+if (( INFLATED_RATES == 1 )); then
+  echo "Sending inflated rates"
+  TRACE_DIR="$INPUT_DIR/trace_inflated"
+else
+  echo "Sending regular rates"
+  TRACE_DIR="$INPUT_DIR/trace"
+fi;
+echo "Path to the trace dir: $TRACE_DIR"
+
 #build the jar
-cd $JAVA_DIR
-mvn clean package
-cd $DEPLOYING_DIR
+cd $JAVA_BASE_DIR && mvn -pl java-cep clean package && cd $DEPLOYING_DIR
 
 #start all nodes
-JAR="$JAVA_DIR/target/beispiel-1.0-SNAPSHOT.jar"
+JAR="$JAVA_PROJ_DIR/target/java-cep-1.0-SNAPSHOT.jar"
 
-#runid=$(date '+%F-%H_%M_%S')
-#runid=$DIR_NAME
-#RESULTS_DIR="$DEPLOYING_DIR/results/$runid"
 RESULTS_DIR=$INPUT_DIR
-#mkdir -p "$RESULTS_DIR/inputs"
-pgrep -f "java -jar" | xargs kill
+ps aux | grep '[j]ava-cep' | awk '{print $2}' | xargs kill -9
+# pgrep -f "java -jar" | xargs kill
 for ((i=0; i<N_NODES; i++)); do
   echo "starting $i"
-  java -ea --add-opens java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.net=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED -jar "$JAR" -localconfig "$INPUT_DIR/config_$i.json" \
-             -flinkconfig "$JAVA_DIR/conf" -globalconfig "$DEPLOYING_DIR/address_book_localhost.json" \
-             -monitoringinputs "$INPUT_DIR/inequality_inputs.json" \
+  java -ea --add-opens java.base/java.lang=ALL-UNNAMED \
+           --add-opens=java.base/java.net=ALL-UNNAMED \
+           --add-opens=java.base/java.util=ALL-UNNAMED \
+            -jar "$JAR" \
+            -flinkconfig "$JAVA_PROJ_DIR/conf" \
+            -localconfig "$INPUT_DIR/config_$i.json" \
+            -globalconfig "$DEPLOYING_DIR/address_book_localhost.json" \
+            -monitoringinputs "$INPUT_DIR/inequality_inputs.json" \
              | tee "$INPUT_DIR/$i.log" 2> >(tee "$INPUT_DIR/$i.err" >&2) &
              # >"$INPUT_DIR/$i.log" 2>"$INPUT_DIR/$i.err" &
 done;
@@ -59,7 +94,7 @@ rm $RESULTS_DIR/py.err
 for ((i=0; i<N_NODES; i++)); do
   echo starting inputs on "$i"
   # TODO: read the ports of the nodes from the config file
-  nohup python3 "$PY_DIR/send_eventstream.py" "$i" -f "$INPUT_DIR/trace_$i.csv" --address-book "$DEPLOYING_DIR/address_book_localhost.json" >>"$RESULTS_DIR/py.log" 2>>"$RESULTS_DIR/py.err" &
+  nohup python3 "$PY_DIR/send_eventstream.py" "$i" -f "$TRACE_DIR/trace_$i.csv" --address-book "$DEPLOYING_DIR/address_book_localhost.json" >>"$RESULTS_DIR/py.log" 2>>"$RESULTS_DIR/py.err" &
   # nohup python3 "$PY_DIR/send_eventstream.py" "$i" -f "$INPUT_DIR/trace_$i.csv" -p $((5500+i)) >"$RESULTS_DIR/py.log" 2>"$RESULTS_DIR/py.err" &
 done
 sleep  $((60 * RUN_DURATION_MIN))
