tmp: load input/output paths from .env files

diff --git a/deploying/run_local b/deploying/run_local
--- a/deploying/run_local
+++ b/deploying/run_local
@@ -6,7 +6,7 @@ JAVA_PROJ_DIR="$BASE_DIR/mama-module/java-cep"
 PY_DIR="$BASE_DIR/python"
 DEPLOYING_DIR="$BASE_DIR/deploying"
 MONITORING_DIR="$BASE_DIR/mama-module/monitoring"
-INFLATED_RATES=0
+
 
 wait_until_middle_of_minute() {
   seconds_on_clock=$(date "+%-S")
@@ -15,11 +15,12 @@ wait_until_middle_of_minute() {
 }
 
 usage() {
-  # echo "Usage: run [OPTIONS] INPUT_DIR TRACE_DIR N [RUN_DURATION]";
-  echo "Usage: run INPUT_DIR TRACE_DIR N [RUN_DURATION]";
+  echo "Usage: run ENV_FILE N [RUN_DURATION]";
   echo "Deploys configs and runs all nodes."
-  echo "INPUT_DIR: path to a folder with config_*.json and trace_*.json for each node";
-  echo "TRACE_DIR: path to a folder with trace_*.csv for each node";
+  echo "ENV_FILE: path to a .env* file with the environment variables INPUT_DIR, OUTPUT_DIR";
+  # echo "INPUT_DIR: path to a folder with config_*.json and trace_*.json for each node";
+  # echo "OUTPUT_DIR: path save node logs";
+  # echo "TRACE_DIR: path to a folder with trace_*.csv for each node";
   echo "N: number of nodes";
   echo "RUN_DURATION: sleep time, i.e. expected duration (default is 10m)";
   echo "";
@@ -27,17 +28,18 @@ usage() {
   # echo "  -i: Flag that enables inflated rates";
 }
 
-if (( $# < 3 )); then
+if (( $# < 2 )); then
   usage
   exit 1
 fi;
 
-INPUT_DIR="$(realpath $1)"
-TRACE_DIR="$(realpath $2)"
+ENV_FILE="$(realpath $1)"
+env $(cat "$ENV_FILE" | xargs)
 N_NODES=$(($3))
 RUN_DURATION_MIN=${4:-10}  # Use the third argument, or set default value
 
 echo "INPUT_DIR: $INPUT_DIR"
+echo "OUTPUT_DIR: $OUTPUT_DIR"
 echo "TRACE_DIR: $TRACE_DIR"
 echo "N_NODES: $N_NODES"
 echo "RUN_DURATION_MIN: $RUN_DURATION_MIN"
@@ -86,52 +88,52 @@ echo "RUN_DURATION_MIN: $RUN_DURATION_MIN"
 # cd $JAVA_BASE_DIR && mvn -pl java-cep clean package && cd $DEPLOYING_DIR
 
 #start all nodes
-JAR="$JAVA_PROJ_DIR/target/java-cep-1.0-SNAPSHOT.jar"
-
-RESULTS_DIR=$INPUT_DIR
-ps aux | grep '[j]ava-cep' | awk '{print $2}' | xargs kill -9
-
-# start monitors
-# $MONITORING_DIR/start_monitoring.sh
-
-for ((i=0; i<N_NODES; i++)); do
-  echo "starting $i"
-  java -ea --add-opens java.base/java.lang=ALL-UNNAMED \
-           --add-opens=java.base/java.net=ALL-UNNAMED \
-           --add-opens=java.base/java.util=ALL-UNNAMED \
-           --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED \
-            -jar "$JAR" \
-            -flinkconfig "$JAVA_PROJ_DIR/conf" \
-            -localconfig "$INPUT_DIR/config_$i.json" \
-            -globalconfig "$DEPLOYING_DIR/address_book_localhost.json" \
-            -monitoringinputs "$INPUT_DIR/inequality_inputs.json" \
-            -updatedrules "$INPUT_DIR/updated_forwared_rules.json" \
-             | tee "$INPUT_DIR/$i.log" 2> >(tee "$INPUT_DIR/$i.err" >&2) &
-             # >"$INPUT_DIR/$i.log" 2>"$INPUT_DIR/$i.err" &
-done;
-
-#check that all processes are running
-
-echo "waiting 10 sec for all nodes to start up..."
-sleep 10
-wait_until_middle_of_minute
-
-#start input srcs
-rm $RESULTS_DIR/py.log
-rm $RESULTS_DIR/py.err
-for ((i=0; i<N_NODES; i++)); do
-  echo starting inputs on "$i"
-  # TODO: read the ports of the nodes from the config file
-  nohup python3 "$PY_DIR/send_eventstream.py" "$i" -f "$TRACE_DIR/trace_$i.csv" --address-book "$DEPLOYING_DIR/address_book_localhost.json" >>"$RESULTS_DIR/py.log" 2>>"$RESULTS_DIR/py.err" &
-  # nohup python3 "$PY_DIR/send_eventstream.py" "$i" -f "$INPUT_DIR/trace_$i.csv" -p $((5500+i)) >"$RESULTS_DIR/py.log" 2>"$RESULTS_DIR/py.err" &
-done
-sleep  $((60 * RUN_DURATION_MIN))
-mkdir "$RESULTS_DIR/mem_usage"
-mkdir "$RESULTS_DIR/throughput"
-# mv mem* "$RESULTS_DIR/mem_usage"
-# mv through* "$RESULTS_DIR/throughput"
-
-#wait for process termination
-ps aux | grep '[j]ava' | grep -v java-language-server | awk '{print $2}' | xargs kill -9
-#clean up ugly empty log files
-#find "$RESULTS_DIR" -size 0 -name '*.err' -exec rm {} ';'
+# JAR="$JAVA_PROJ_DIR/target/java-cep-1.0-SNAPSHOT.jar"
+#
+# RESULTS_DIR=$INPUT_DIR
+# ps aux | grep '[j]ava-cep' | awk '{print $2}' | xargs kill -9
+#
+# # start monitors
+# # $MONITORING_DIR/start_monitoring.sh
+#
+# for ((i=0; i<N_NODES; i++)); do
+#   echo "starting $i"
+#   java -ea --add-opens java.base/java.lang=ALL-UNNAMED \
+#            --add-opens=java.base/java.net=ALL-UNNAMED \
+#            --add-opens=java.base/java.util=ALL-UNNAMED \
+#            --add-opens java.base/java.util.concurrent.atomic=ALL-UNNAMED \
+#             -jar "$JAR" \
+#             -flinkconfig "$JAVA_PROJ_DIR/conf" \
+#             -localconfig "$INPUT_DIR/config_$i.json" \
+#             -globalconfig "$DEPLOYING_DIR/address_book_localhost.json" \
+#             -monitoringinputs "$INPUT_DIR/inequality_inputs.json" \
+#             -updatedrules "$INPUT_DIR/updated_forwared_rules.json" \
+#              | tee "$INPUT_DIR/$i.log" 2> >(tee "$INPUT_DIR/$i.err" >&2) &
+#              # >"$INPUT_DIR/$i.log" 2>"$INPUT_DIR/$i.err" &
+# done;
+#
+# #check that all processes are running
+#
+# echo "waiting 10 sec for all nodes to start up..."
+# sleep 10
+# wait_until_middle_of_minute
+#
+# #start input srcs
+# rm $RESULTS_DIR/py.log
+# rm $RESULTS_DIR/py.err
+# for ((i=0; i<N_NODES; i++)); do
+#   echo starting inputs on "$i"
+#   # TODO: read the ports of the nodes from the config file
+#   nohup python3 "$PY_DIR/send_eventstream.py" "$i" -f "$TRACE_DIR/trace_$i.csv" --address-book "$DEPLOYING_DIR/address_book_localhost.json" >>"$RESULTS_DIR/py.log" 2>>"$RESULTS_DIR/py.err" &
+#   # nohup python3 "$PY_DIR/send_eventstream.py" "$i" -f "$INPUT_DIR/trace_$i.csv" -p $((5500+i)) >"$RESULTS_DIR/py.log" 2>"$RESULTS_DIR/py.err" &
+# done
+# sleep  $((60 * RUN_DURATION_MIN))
+# mkdir "$RESULTS_DIR/mem_usage"
+# mkdir "$RESULTS_DIR/throughput"
+# # mv mem* "$RESULTS_DIR/mem_usage"
+# # mv through* "$RESULTS_DIR/throughput"
+#
+# #wait for process termination
+# ps aux | grep '[j]ava' | grep -v java-language-server | awk '{print $2}' | xargs kill -9
+# #clean up ugly empty log files
+# #find "$RESULTS_DIR" -size 0 -name '*.err' -exec rm {} ';'
